// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Forest")]
[assembly: AssemblyProductAttribute("Plainion.Forest")]
[assembly: AssemblyDescriptionAttribute("Plainion.Forest")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Forest";
        internal const System.String AssemblyProduct = "Plainion.Forest";
        internal const System.String AssemblyDescription = "Plainion.Forest";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.1.0";
        internal const System.String AssemblyFileVersion = "1.1.0";
    }
}
